name: 'Build Krsistal mod'
description: 'Compiles a Kristal mod into a TARGET_MOD engine build'
runs:
  using: composite
  steps:
    - run: python3 $GITHUB_ACTION_PATH/pre.py
      shell: bash
    - run: python3 $GITHUB_ACTION_PATH/main.py
      shell: bash

