# If you want to use this as-is, put it in .github/workflows/ci.yml.
name: CI

on: [push, pull_request]

jobs:
  build-linux:
    name: Build (ubuntu)

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ./mod

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ./kristal
          repository: KristalTeam/Kristal

      - name: Install Dependencies
        run: |
          pip3 install pe_tools

      - name: Download LÖVE
        run: |
          curl -L https://github.com/love2d/love/releases/download/11.5/love-11.5-win64.zip -o love.zip
          7z x love.zip
          rm love.zip

      - name: Build
        uses: Hyperboid/build-mod@v0.1.0

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: ./output